{% set name = "pyneval" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 64f01e26f57fe78be46d13731718acf318661c06063672a8473a447a2bfcdc43

build:
  number: 0
  entry_points:
    - pyneval=pyneval.cli.pyneval:run
    - pyneval_tools=pyneval.cli.pyneval_tools:run
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip>=21.1.2
    - python>=3.7
  run:
    - anytree>=2.7.2
    - jsonschema>=3.2.0
    - kdtree>=0.16
    - numpy>=1.0
    - python>=3.7
    - rtree>=0.8

test:
  imports:
    - pyneval
    - pyneval.cli
    - pyneval.io
    - pyneval.metric
    - pyneval.metric.utils
    - pyneval.metric.utils.klib
    - pyneval.model
    - pyneval.tools
    - pyneval.tools.optimize
    - test
  commands:
    - pyneval --help
    - pyneval_tools --help

about:
  home: "https://github.com/CSDLLab/PyNeval"
  license: GPL
  license_family: GPL
  license_file: LICENSE.txt
  summary: "pyneval, a toolbox for quantitative metric on reconstructed neuron"
  doc_url: "https://csdllab.github.io/PyNeval"
  dev_url: "https://github.com/CSDLLab/PyNeval"

extra:
  recipe-maintainers:
    - benniehan
